Extracting Data from yfinance and preprocessing and saving onto a MongoDB database

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (0.2.33)
Requirement already satisfied: pandas>=1.3.0 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/moritzrichter/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2024.2.2)

In [8]:
# Import DataReader from pandas_datareader to fetch financial data from various Internet sources
from pandas_datareader.data import DataReader
# Import yfinance, an alternative library that accesses Yahoo Finance data, and overrides pandas_datareader's default methods
import yfinance as yf
from pandas_datareader import data as pdr

# Apply yfinance's override to pandas_datareader's methods to improve data fetching reliability and speed
yf.pdr_override()

# Import datetime for handling and formatting date objects
from datetime import datetime, timedelta

# Define the stock symbol for the S&P 500 as used in Yahoo Finance's listings
stock_symbol = "^GSPC"
# Set the start date for historical data retrieval to 5 years ago from today
start_date = (datetime.today() - timedelta(days=5*365)).strftime('%Y-%m-%d')
# Set the end date for the data retrieval to today's date, formatted as 'YYYY-MM-DD'
end_date = datetime.today().strftime('%Y-%m-%d')

# Fetch historical S&P 500 data from Yahoo Finance using the defined time range
sp500_data = yf.download(stock_symbol, start=start_date, end=end_date)

# Display the fetched data to check its contents and structure
S_P_df = sp500_data
S_P_df

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-16,2912.260010,2916.060059,2900.709961,2907.060059,2907.060059,3403120000
2019-04-17,2916.040039,2918.000000,2895.449951,2900.449951,2900.449951,3648100000
2019-04-18,2904.810059,2908.399902,2891.899902,2905.030029,2905.030029,3507100000
2019-04-22,2898.780029,2909.510010,2896.350098,2907.969971,2907.969971,3010130000
2019-04-23,2909.989990,2936.310059,2908.530029,2933.679932,2933.679932,3674480000
...,...,...,...,...,...,...
2024-04-08,5211.370117,5219.569824,5197.350098,5202.390137,5202.390137,3278180000
2024-04-09,5217.029785,5224.810059,5160.779785,5209.910156,5209.910156,3400680000
2024-04-10,5167.879883,5178.430176,5138.700195,5160.640137,5160.640137,3845930000
2024-04-11,5172.950195,5211.779785,5138.770020,5199.060059,5199.060059,3509380000
2024-04-12,5171.509766,5175.029785,5107.939941,5123.410156,5123.410156,3963220000

In [12]:
import pandas as pd

S_P_df.reset_index(inplace=True)

# Now 'Date' is a regular column in the DataFrame
print(S_P_df.head())  # Display the first few rows to verify the changes

        Date         Open         High          Low        Close    Adj Close  \
0 2019-04-16  2912.260010  2916.060059  2900.709961  2907.060059  2907.060059
1 2019-04-17  2916.040039  2918.000000  2895.449951  2900.449951  2900.449951
2 2019-04-18  2904.810059  2908.399902  2891.899902  2905.030029  2905.030029
3 2019-04-22  2898.780029  2909.510010  2896.350098  2907.969971  2907.969971
4 2019-04-23  2909.989990  2936.310059  2908.530029  2933.679932  2933.679932

       Volume
0  3403120000
1  3648100000
2  3507100000
3  3010130000
4  3674480000

In [13]:
# checking for mull values
S_P_df.isnull().sum().sum()
S_P_df.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [14]:
# Define the file path where you want to save the CSV
file_path = '/Users/moritzrichter/Desktop/cryptocurrency_analysis/stock_market/S_P(fiveyears).csv'

# Save the DataFrame to CSV at the specified path
S_P_df.to_csv(file_path, index=False)  # `index=False` to prevent writing row indices in the file